version: "3.8"

services:
  web:
    build:
      context: .
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    working_dir: /app/backend
    command: python manage.py runserver 0.0.0.0:8000
